### ISSUE TITLE
Пожалуйста омогите разобраться

### ISSUE THREAD

**Issue by olga028383** [bem/bem-method#370]
Здравствуйте, я только учусь и сразу возникает много вопросов.
Один из них?
мы выделяем отдельные самостоятельные блоки, 
например p-параграф, раньше мы писали в css 
`p{}`
теперь создаем для него `class="paragraph"` и css
```css
.paragraph {
    font-size: 12px;
    font-weight: bold;
}
```
но наш параграф находится 
1) в контекте блока с классом news, если я верно поняла то теперь класс будет такой 
```css
news__paragraph {
    font-size: 12px;
    font-weight: bold;
}
```
2) в контекте блока с классом `question`, если я верно поняла, то теперь класс будет такой 
```css
.question__paragraph {
    font-size: 12px;
    font-weight: bold;
}
```

Если у тега `p` одинаковые стили в разных контекстах, получается дублирование. А если мы зададим `<p class="paragraph"></p>` Тогда он выпадет из контекста. Как быть в таком случае, пожалуйста, приведите пример.
